Fix deployment error due to improperly types params
Fix the following error by typing `params` as `Promise<Params>`:

```
app/listings/[listingId]/page.tsx
Type error: Type '{ params: Params; }' does not satisfy the constraint 'PageProps'.
  Types of property 'params' are incompatible.
    Type 'Params' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]
Next.js build worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1
```