Type searchParams in Home as a Promise
I'm getting the following error when trying to deploy.

Type the searchParams as a Promise in an atempt to fix:

```
app/page.tsx
Type error: Type '{ searchParams: IListingsParams; }' does not satisfy the constraint 'PageProps'.
  Types of property 'searchParams' are incompatible.
    Type 'IListingsParams' is missing the following properties from type 'Promise<any>': then, catch, finally, [Symbol.toStringTag]
Next.js build worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1
```