Add not-found.tsx page
When deploying to Vercel, I got the following error. This is an attempt to fix
that:

Error: Dynamic server usage: Route /_not-found couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at m (.next/server/chunks/447.js:19:10449)
    at d (.next/server/chunks/495.js:34:32766)
    at s (.next/server/chunks/495.js:17:22884)
    at h (.next/server/chunks/669.js:9:2218)
    at m (.next/server/chunks/669.js:9:2250)
    at m (.next/server/chunks/669.js:19:1878) {
  description: "Route /_not-found couldn't be rendered statically because it used `headers`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
  digest: 'DYNAMIC_SERVER_USAGE'
}
 ⨯ useSearchParams() should be wrapped in a suspense boundary at page "/404". Read more: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
    at t (/vercel/path0/.next/server/chunks/246.js:3:11629)
    at f (/vercel/path0/.next/server/chunks/246.js:183:42490)
    at f (/vercel/path0/.next/server/chunks/669.js:31:828)
    at nF (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:46843)
    at nH (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:48618)
    at nH (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:64688)
    at nW (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:67762)
    at nz (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:65337)
    at nY (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:71193)
    at nX (/vercel/path0/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:76:69876)
Error occurred prerendering page "/_not-found". Read more: https://nextjs.org/docs/messages/prerender-error
Export encountered an error on /_not-found/page: /_not-found, exiting the build.
 ⨯ Next.js build worker exited with code: 1 and signal: null
Error: Command "npm run build" exited with 1